export const items = [
  {
    id: Math.random(),
    title: 'Mens',
    description: 'Mens T-shirt',
    price: '50$',
    category: 'Mens',
    imgUrl: 'men1.webp',
  },
  {
    id: Math.random(),
    title: 'Mens',
    description: 'Mens T-shirt',
    price: '60$',
    category: 'Mens',
    imgUrl: 'men3.webp',
  },
  {
    id: Math.random(),
    title: 'Mens',
    description: 'Mens T-shirt',
    price: '60$',
    category: 'Mens',
    imgUrl: 'men2.webp',
  },
  {
    id: Math.random(),
    title: 'Mens',
    description: 'Mens T-shirt',
    price: '60$',
    category: 'Mens',
    imgUrl: 'men4.webp',
  },
  {
    id: Math.random(),
    title: 'Women',
    description: 'Women T-shirt',
    price: '90$',
    category: 'Womens',
    imgUrl: 'women1.webp',
  },
  {
    id: Math.random(),
    title: 'Women',
    description: 'Women T-shirt',
    price: '90$',
    category: 'Womens',
    imgUrl: 'women2.webp',
  },
  {
    id: Math.random(),
    title: 'Women',
    description: 'Women T-shirt',
    price: '90$',
    category: 'Womens',
    imgUrl: 'women3.webp',
  },
  {
    id: Math.random(),
    title: 'Women',
    description: 'Women T-shirt',
    price: '90$',
    category: 'Womens',
    imgUrl: 'women4.jpg',
  },
  {
    id: Math.random(),
    title: 'Youth',
    description: 'Youth T-shirt',
    price: '70$',
    category: 'Youth',
    imgUrl: 'youth1.webp',
  },
  {
    id: Math.random(),
    title: 'Youth',
    description: 'Youth T-shirt',
    price: '70$',
    category: 'Youth',
    imgUrl: 'youth2.webp',
  },
  {
    id: Math.random(),
    title: 'Youth',
    description: 'Youth T-shirt',
    price: '70$',
    category: 'Youth',
    imgUrl: 'youth3.webp',
  },
  {
    id: Math.random(),
    title: 'Youth',
    description: 'Youth T-shirt',
    price: '70$',
    category: 'Youth',
    imgUrl: 'youth4.webp',
  },
]
